<?php

function randomIngredientName()
{
    $ingredients = [
        "Ser mozzarella",
        "Pieczarki",
        "Szynka parmeńska",
        "Salami",
        "Papryka",
        "Cebula czerwona",
        "Oliwki",
        "Ananas",
        "Sos pomidorowy",
        "Kurczak",
        "Krewetki",
        "Bazylia",
        "Sos BBQ",
        "Parmezan",
        "Czosnek",
        "Tuńczyk",
        "Sos czosnkowy",
        "Sos chili",
        "Ser feta",
        "Brokuły",
        "Sos pesto",
        "Ser pleśniowy",
        "Sos curry",
        "Zioła prowansalskie",
        "Ser cheddar",
        "Sos tzatziki",
        "Papryczki jalapeño",
        "Kukurydza",
        "Cukinia",
        "Bakłażan",
        "Rukola",
        "Słonecznik",
        "Orzechy włoskie",
        "Słodka papryka",
        "Kardamon",
        "Gałka muszkatołowa",
        "Pietruszka",
        "Boczek",
        "Szpinak",
        "Karczochy",
        "Pomidory suszone",
        "Pomidory koktajlowe",
        "Czerwona fasola",
        "Szparagi",
        "Gruszka",
        "Gorgonzola",
        "Prosciutto",
        "Chorizo",
        "Jalapeño świeże",
        "Czerwona cebula",
        "Pieczona papryka",
        "Ricotta",
        "Ser kozi",
        "Mango",
        "Rzeżucha",
        "Kiełki",
        "Sos śmietanowy",
        "Sos serowy",
        "Sos pomidorowy pikantny",
        "Kabanos",
        "Kiełbasa wiejska",
        "Ogórek konserwowy",
        "Ogórek świeży",




    ];
    return $ingredients[array_rand($ingredients)];
}
